### ISSUE TITLE
/libspconv.so: file format not recognized

### ISSUE THREAD

**Issue by whw12345** [NVIDIA-AI-IOT/Lidar_AI_Solution#17]
CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: file format not recognized; treating as linker script

**Comment by hopef** [comment]
You need to install git-lfs and then pull the repository because the so files are stored using git-lfs.


Or download the so file directly manually.



------------------ Original ------------------
From: whw12345 ***@***.***&gt;
Date: Sat,May 20,2023 0:34 AM
To: NVIDIA-AI-IOT/Lidar_AI_Solution ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [NVIDIA-AI-IOT/Lidar_AI_Solution] /libspconv.so: file format not recognized (Issue #17)





 
CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: file format not recognized; treating as linker script

**Comment by whw12345** [comment]
I want to download the so file directly manually，where is the address？

**Comment by shuyuan-wang** [comment]
https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so

Click view raw I guess? For x86

**Comment by czd2003** [comment]
ERROR like this:

/Lidar_AI_Solution/CUDA-CenterPoint/3rdparty/libspconv/lib/x86_64/libspconv.so: undefined reference to `google::protobuf::

**Comment by xqh5201314** [comment]
> 

do you slove this? i have same error.

**Comment by wanglaotou** [comment]
> I want to download the so file directly manually，where is the address？
cd Lidar_AI_Solution/libraries/3DSparseConvolution/libspconv/lib/x86_64/

wget https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so

and i still get the same error, how to solve this problem, thanks.

Lidar_AI_Solution/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status

**Comment by mchi-zg** [comment]
Hi @wanhlaotou, sorry for deleting you comment by mistake. :(

**Comment by HZQNPU** [comment]
How to do after installing git lfs?

**Comment by wanglaotou** [comment]
@hopef hello, this issue has not been solved, why you close this issue.
i run this command like this:
wget https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so
and i run bash tool/run.sh, the error "x86_64/libspconv.so: file format not recognized" still exist, could you please tell me how to solve this problem, thanks.

**Comment by hopef** [comment]
You need to download it by `mouse click`, not by `wget`.
